### ISSUE TITLE
[Todo] Create a blog

### ISSUE THREAD

**Issue by luiscarbonell** [luiscarbonell/luiscarbonell.github.io#2]
### Self-Hosted Blogging Platforms

* [ ] [Ghost](https://ghost.org/)
* [ ] [Bludit](https://www.bludit.com)
* [ ] [Hexo](https://hexo.io)
* [ ] [Kwon](https://withknown.com/)

**Alternatives**
* [ ] [Plume](https://joinplu.me/)
